// src/data.js
export const products = [
    {
        id: 1,
        title: "Radiant Glow Serum",
        description: "A powerful serum packed with Vitamin C and Hyaluronic Acid to brighten and hydrate your skin.",
        price: 45.00,
        rating: 4.8,
        image: "https://i.imgur.com/vptiD3s.jpeg",
        createdAt: "2025-07-26T10:00:00Z",
    },
    {
        id: 2,
        title: "Matte Finish Foundation",
        description: "Long-lasting, full-coverage foundation with a flawless matte finish. Available in 20 shades.",
        price: 38.50,
        rating: 4.5,
        image: "https://i.imgur.com/nJhlL72.jpeg",
        createdAt: "2025-07-25T11:30:00Z",
    },
    {
        id: 3,
        title: "Volumizing Mascara",
        description: "Get dramatic volume and length with this smudge-proof, long-wearing mascara.",
        price: 24.00,
        rating: 4.7,
        image: "https://i.imgur.com/gO0aYEr.jpeg",
        createdAt: "2025-07-27T09:00:00Z",
    },
    {
        id: 4,
        title: "Hydrating Lip Balm SPF 30",
        description: "Nourish and protect your lips with this ultra-hydrating balm with sun protection.",
        price: 12.00,
        rating: 4.9,
        image: "https://i.imgur.com/5JpZEWN.jpeg",
        createdAt: "2025-07-24T14:00:00Z",
    },
    {
        id: 5,
        title: "Cleansing Clay Mask",
        description: "A detoxifying clay mask that purifies pores and leaves skin feeling refreshed.",
        price: 29.99,
        rating: 4.6,
        image: "https://i.imgur.com/k2psCHT.jpeg",
        createdAt: "2025-07-26T18:00:00Z",
    },
    {
        id: 6,
        title: "Rosewater Facial Mist",
        description: "A refreshing facial mist to soothe and hydrate skin throughout the day.",
        price: 18.00,
        rating: 4.7,
        image: "https://i.imgur.com/5u0w3qC.jpeg",
        createdAt: "2025-07-27T12:15:00Z",
    }
];